---
-
  hosts: appservers
  become: yes
  become_method: sudo

  tasks:
    - name: tomcat stop
      service: name=tomcat8 state=stopped

    - name: delete war file in tomcat webapps
      file: path=/var/lib/tomcat8/webapps/app.war

    - name: Copying the local app.war file on remote
      become: true
      copy:
        src: /var/lib/jenkins/workspace/App-Build-Deploy/target/app.war
        dest: /var/lib/tomcat8/webapps/
      notify: start tomcat

  handlers:
    - name: start tomcat
      service: name=tomcat8 state=started
